apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: volantebjb/neutrino-web-app
        imagePullPolicy: Always
        env:
          - name: NEXTAUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: web-app-secret
                key: authSecret
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: web-app-secret
                key: clientSecret
          - name: NEXTAUTH_URL
            value: https://www.neutrino.live
          - name: API_URL
            value: http://gateway-clusterip/
          - name: ID_URL
            value: https://id.neutrino.live
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-clusterip
spec:
  type: ClusterIP
  selector:
    app: web-app
  ports:
  - port: 3000
    targetPort: 3000

